### ISSUE TITLE
Never returns via browser with localstack but returns without closing connection with invoke

### ISSUE THREAD

**Issue by davidrhoderick** [MatteoGioioso/serverless-pg#41]
I had the same problem with `serverless-mysql` and posted an issue there but never got a response.  I'm sure I'm just not using this plugin right and while it may be a basic configuration/function issue, I feel like there should be pointers on how to use this plugin if you are relatively new to `node-pg` and `serverless`.  Here's my `handler.js`:

```
const ServerlessClient = require('serverless-postgres')

const client = new ServerlessClient({
  user: process.env.DB_USERNAME,
  host: process.env.DB_HOST,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  debug: true,
  delayMs: 3000,
})

exports.hello = async (event) => { // This works
  const { name = '' } = event.body || {}

  return {
    statusCode: 200,
    body: `Hello ${name} 👋`,
  }
}

exports.testdb = async () => { // This hangs and creates a lambda docker that does nothing
  await client.connect()
  
  const result = await client.query(`SELECT * from test`)
  
  await client.clean()

  return {
    body: {message: result.rows[0]},
    statusCode: 200
  }
}
```

According to the documentation, the `testdb` function should work as written but it just hangs.  On running `sls invoke --function testdb`, I get a result plus debug messages but I have to end the process manually.

**Comment by MatteoGioioso** [comment]
Hello @davidrhoderick as my understanding this happening only through localstack am I right?
Could you please paste the `serverless.yml` or any configuration related to localstack as well? 
Thanks

**Comment by davidrhoderick** [comment]
Correct, this is through localstack.  Here's my `serverless.yml`:

```
org: someorg
app: someapp
service: api

frameworkVersion: '2'

disabledDeprecations:
  - CLI_OPTIONS_SCHEMA

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true
    lambda:
      mountCode: false
    docker:
      sudo: false

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: local
  environment:
    DB_HOST: 172.20.0.2
    DB_NAME: postgres
    DB_USERNAME: some_user
    DB_PASSWORD: password
    
functions:
  hello:
    handler: ./handler.hello
    events:
      - http:
          path: hello
          method: GET
          cors: true
  testdb:
    handler: ./handler.testdb
    events:
      - http:
          path: testdb
          method: GET
          cors: true

plugins:
  - serverless-localstack
```
